on:
  workflow_dispatch:
    inputs:
      filepath:
        description: Path to the Markdown paper file.
        required: true
        type: string
        default: joss/paper.md
jobs:
  open-journals:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        journal: [ joss, jose, resciencec ]
        output: [ pdf,jats,html,crossref,cff,preprint,docx,native,tex,shared,contextpdf ]
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Directory Location
        id: loc
        run: |
          dirpath=$(dirname "${{ inputs.filepath }}")
          echo "$dirpath"
          echo "dirpath=$dirpath" >> $GITHUB_ENV
      - name: Directory Pre-Scan
        id: state-before
        run: |
          before=$(find "repo/$dirpath")
          echo "$before"
          {
            echo 'before<<EOF'
            echo $before
            echo EOF
          } >> "$GITHUB_ENV"
      - name: Build
        uses: docker://openjournals/inara:latest
        env:
          JOURNAL: ${{ matrix.journal }}
        with:
          args: -o ${{ matrix.output }} repo/${{ inputs.filepath }}
      - name: Directory Post-Scan
        id: state-after
        run: |
          after=$(find "repo/$dirpath")
          echo "$after"
          {
            echo 'after<<EOF'
            echo $after
            echo EOF
          } >> "$GITHUB_ENV"
      - name: Output Identification
        run: |
          before=($before)
          after=($after)
          output_paths=""
          for item in "${after[@]}"; do
            if [[ ! " ${before[@]} " =~ " $item " ]]; then
              output_paths+="$item"$'\n'
            fi
          done
          echo "$output_paths"
          {
            echo 'output_paths<<EOF'
            echo $output_paths
            echo EOF
          } >> "$GITHUB_ENV"
      - name: Artifact Generation
        run: |          
          mkdir -p output
          sudo chown -R runner:docker "repo/$dirpath"
          output_paths=($output_paths)
          for new_item in "${output_paths[@]}"; do
            # Check if the parent directory has already been moved
            if [[ ! -e "$new_item" ]]; then
              echo "Skipping $new_item: already moved as part of its parent directory."
              continue
            fi
            echo "Moving $new_item"
            mv "$new_item" output/
          done
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper-${{matrix.journal}}-${{matrix.output}}
          path: output
      # - name: Build
      #   uses: docker://openjournals/inara:latest
      #   env:
      #     JOURNAL: ${{ matrix.journal }}
      #   with:
      #     args: -p joss/paper.md
      # - run: |
      #     find .
      # - name: Upload
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: paper2
      #     # This is the output path where Pandoc will write the compiled
      #     # PDF. Note, this should be the same directory as the input
      #     # paper.md
      #     path: joss
  wheel-merge:
    name: Artifact Merge
    if: ${{ !cancelled() }}
    needs: [ open-journals ]
    runs-on: ubuntu-latest
    steps:
      - name: Merge
        uses: actions/upload-artifact/merge@v4
        with:
          name: paper
          pattern: paper-*
          separate-directories: 'true'
          delete-merged: 'true'
