name: Open Journals
on:
  workflow_dispatch:
    inputs:
      filepath:
        description: Path to the Markdown paper file.
        required: true
        type: string
        default: joss/paper.md
      journal:
        description: Journal
        required: true
        default: JOSS
        type: choice
        options:
          - JOSS
          - JOSE
          - ReScience C
      ref:
        description: Git reference
        required: false
        type: string
      repository:
        description: GitHub repository
        required: false
        type: string
jobs:
  build:
    name: ${{ matrix.output.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        output:
          - name: PDF (final)
            arg: -p
          - name: PDF (draft)
            arg: -o pdf
          - name: PDF (context)
            arg: -o contextpdf
          - name: LaTeX
            arg: -o tex
          - name: LaTeX (preprint)
            arg: -o preprint
          - name: Word DOCX
            arg: -o docx
          - name: JATS
            arg: -o jats
          - name: HTML
            arg: -o html
          - name: CrossRef
            arg: -o crossref
          - name: CFF
            arg: -o cff
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || github.ref }}
          path: repo
      - name: Directory Location
        id: loc
        run: |
          dirpath=$(dirname "${{ inputs.filepath }}")
          echo "$dirpath"
          echo "dirpath=$dirpath" >> $GITHUB_ENV
      - name: Directory Pre-Scan
        id: state-before
        run: |
          files_before=$(find "repo/$dirpath")
          echo "$files_before"
          {
            echo 'files_before<<EOF'
            echo $files_before
            echo EOF
          } >> "$GITHUB_ENV"
      - name: Journal Determination
        run: |
          journal=$(echo "${{ inputs.journal }}" | tr '[:upper:]' '[:lower:]' | tr -d ' ')
          echo "JOURNAL=$journal" >> $GITHUB_ENV
      - name: Build
        uses: docker://openjournals/inara:latest
        with:
          args: ${{ matrix.output.arg }} repo/${{ inputs.filepath }}
      - name: Directory Post-Scan
        id: state-after
        run: |
          files_after=$(find "repo/$dirpath")
          echo "$files_after"
          {
            echo 'files_after<<EOF'
            echo $files_after
            echo EOF
          } >> "$GITHUB_ENV"
      - name: Output Identification
        run: |
          before=($files_before)
          after=($files_after)
          output_paths=""
          for item in "${after[@]}"; do
            if [[ ! " ${before[@]} " =~ " $item " ]]; then
              output_paths+="$item"$'\n'
            fi
          done
          echo "$output_paths"
          {
            echo 'output_paths<<EOF'
            echo $output_paths
            echo EOF
          } >> "$GITHUB_ENV"
      - name: Artifact Generation
        run: |          
          mkdir -p output
          sudo chown -R runner:docker "repo/$dirpath"
          output_paths=($output_paths)
          for new_item in "${output_paths[@]}"; do
            # Check if the parent directory has already been moved
            if [[ ! -e "$new_item" ]]; then
              echo "Skipping $new_item: already moved as part of its parent directory."
              continue
            fi
            echo "Moving $new_item"
            mv "$new_item" output/
          done
      - name: Artifact Overview
        run: tree output
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper-${{matrix.output.name}}
          path: output
      
  wheel-merge:
    name: Artifact Merge
    if: ${{ !cancelled() }}
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Merge
        uses: actions/upload-artifact/merge@v4
        with:
          name: paper
          pattern: paper-*
          separate-directories: 'true'
          delete-merged: 'true'
