name: Open Journals
on:
  workflow_dispatch:
    inputs:
      filepath:
        description: Path to the Markdown paper file.
        required: true
        type: string
        default: docs/papers/joss/paper.md
      journal:
        description: Journal
        required: true
        default: JOSS
        type: choice
        options:
          - JOSS
          - JOSE
          - ReScience C
      ref:
        description: Git reference
        required: false
        type: string
      repository:
        description: GitHub repository
        required: false
        type: string
jobs:
  build:
    name: ${{ matrix.output.name }}
    runs-on: ubuntu-latest
    outputs:
      artifact-base-name: ${{ steps.artifact-name-gen.outputs.artifact_base_name }}
    strategy:
      fail-fast: false
      matrix:
        output:
          - name: PDF (final)
            arg: -p
            paths:
              - output: paper.pdf
              - output: jats
          - name: PDF (draft)
            arg: -o pdf
            paths:
              - output: paper.pdf
                renamed: draft.pdf
          - name: PDF (context)
            arg: -o contextpdf
            paths:
              - output: paper.context.pdf
                renamed: context.pdf
          - name: LaTeX
            arg: -o tex
            paths:
              - output: paper.tex
          - name: LaTeX (preprint)
            arg: -o preprint
            paths:
              - output: paper.preprint.tex
                renamed: draft.tex
          - name: Word DOCX
            arg: -o docx
            paths:
              - output: paper.docx
          - name: HTML
            arg: -o html
            paths:
              - output: paper.html
                renamed: index.html
              - output: media
          - name: CrossRef
            arg: -o crossref
            paths:
              - output: paper.crossref
                renamed: crossref.xml
          - name: CFF
            arg: -o cff
            paths:
              - output: CITATION.cff
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || github.ref }}
      - name: Directory Location
        run: |
          dirpath=$(dirname "${{ inputs.filepath }}")
          echo "$dirpath"
          echo "DIRPATH=$dirpath" >> $GITHUB_ENV
      - name: Directory Overview
        run: tree $DIRPATH
      - name: Directory Cleanup
        run: |
          output_json='${{ toJSON(matrix.output) }}'
          echo "$output_json" | jq -c '.paths[]' | while read -r path; do
            output_path=$(echo "$path" | jq -r '.output')
            rm -rf "${DIRPATH}/${output_path}" 2>/dev/null || echo "Path '${DIRPATH}/${output_path}' does not exist; skipping removal."
          done
      - name: Directory Overview
        run: tree $DIRPATH
      - name: Journal Determination
        run: |
          journal=$(echo "${{ inputs.journal }}" | tr '[:upper:]' '[:lower:]' | tr -d ' ')
          echo "JOURNAL=$journal" >> $GITHUB_ENV
      - name: Build
        uses: docker://openjournals/inara:latest
        with:
          args: ${{ matrix.output.arg }} ${{ inputs.filepath }}
      - name: Output Rename
        run: |
          output_json='${{ toJSON(matrix.output) }}'
          echo "$output_json" | jq -c '.paths[]' | while read -r path; do
            if echo "$path" | jq -e 'has("renamed")' >/dev/null; then
              output_path=$(echo "$path" | jq -r '.output')
              new_path=$(echo "$path" | jq -r '.renamed')
              echo "Renaming '$output_path' to '$new_path'"
              mv "${DIRPATH}/${output_path}" "${DIRPATH}/${new_path}"
            fi
          done
      - name: Directory Overview
        run: tree $DIRPATH
      - name: Artifact Generation
        run: |          
          upload_paths=""
          output_json='${{ toJSON(matrix.output) }}'
          mapfile -t paths < <(echo "$output_json" | jq -c '.paths[]')
          for path in "${paths[@]}"; do
            if echo "$path" | jq -e 'has("renamed")' >/dev/null; then
              upload_path=$(echo "$path" | jq -r '.renamed')
            else
              upload_path=$(echo "$path" | jq -r '.output')
            fi
            upload_paths+="${DIRPATH}/${upload_path}"$'\n'
          done
          {
            echo 'UPLOAD_PATHS<<EOF'
            echo "$upload_paths"
            echo EOF
          } >> "$GITHUB_ENV"
      - name: Artifact Name Generation
        id: artifact-name-gen
        run: >-
          name="paper
          - ${{ inputs.repository || github.repository }}
          - ${{ inputs.ref || github.ref }}
          - ${{ inputs.filepath }}
          - ${{ inputs.journal }}"
          name_normalized=$(echo "$name" | tr '":<>|*?\/' '-')
          echo "artifact_base_name=$name_normalized" >> $GITHUB_OUTPUT
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact-name-gen.outputs.artifact_base_name }} - ${{ matrix.output.name }}
          path: ${{ env.UPLOAD_PATHS }}
  wheel-merge:
    name: Artifact Merge
    if: ${{ !cancelled() }}
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Merge
        uses: actions/upload-artifact/merge@v4
        with:
          name: paper
          pattern: ${{ needs.build.outputs.artifact-base-name }} - *
          separate-directories: 'false'
          delete-merged: 'true'
